version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: Go "
    assignees:
      - "LeMyst"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: Docker "
    assignees:
      - "LeMyst"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: Github Actions "
    assignees:
      - "LeMyst"
