name: nightly
on:
  schedule:
    - cron: '2 2 * * *'
  workflow_dispatch:
jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          set-safe-directory: true
      - name: Set tag name
        id: git_tag
        run: echo "::set-output name=tag::$(git describe --tags --match '[0-9].[0-9].[0-9]')"
      - name: check if tag exists
        id: tag_exists
        run: |
          set -x
          exists=false
          [ "$(git tag -l "${TAG}")" = "${TAG}" ] && exists=true
          [ "$(git tag -l "nightly-${TAG}")" = "nightly-${TAG}" ] && exists=true
          echo "::set-output name=result::${exists}"
        env:
          TAG: ${{ steps.git_tag.outputs.tag }}
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/nightly-${{ steps.git_tag.outputs.tag }}',
              sha: context.sha
            })
        if: ${{ steps.tag_exists.outputs.result != 'true' }}
