name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          exempt-issue-labels: 'awaiting-approval,work-in-progress,not-stale'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,not-stale'
          days-before-stale: 60
          days-before-close: 30
          stale-issue-message: 'This issue has not seen any activity in last 60 days, and has been marked as stale.'
          stale-pr-message: 'This PR has not seen any activity in last 60 days and has been marked as stale'
          close-issue-message: 'This issue was closed because it has been stalled for 90 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 90 days with no activity.'
